version: '3'

silent: true

tasks:

  clean:
    desc: Clean built artefacts
    cmds:
      - cmd: rm -rf book

  serve:
    desc: Start the notes server locally
    cmds:
      - task: clean
      - cmd: mdbook serve || true

  build:
    desc: Build the notes
    cmds:
      - task: clean
      - cmd: mdbook build
